### ISSUE TITLE
Shall we make EUPATH:0000376 'relationship to head of family' more general?

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#138]
EUPATH:0000376 'relationship to head of family'

Definition: an information   content entity that specifies the relationship between a participant under   investigation and the head of the participant's household

Logical definition:
'is about' some   ('family relationship' and ('inheres in' some 'participant under investigation'))

Do we want to make it more general, extend to all human rather than restricted to 'participant under investigation'?

**Comment by johnwjudkins** [comment]
I suggest substituting "household" for "family" in the label. It's used that way in ClinEpi, and it's more general and easier to define.

Regarding references to PUI in definitions, I suggest making them more general (removing PUI in these definitions) excluding the terms for which the necessary context is an investigation/study/experiment. 'immediate history' is a good example of a term that should keep the PUI reference, because it mentions enrollment.

**Comment by cstoeckert** [comment]
current definition: An information content entity that specifies the relationship between a participant under investigation and the head of the participant's household 
proposed definition: An information content entity that specifies the relationship between a person and the head of their household. 

Also change label to: 'relationship to head of household'

Agree these changes are close enough to reuse the IRI.
