### ISSUE TITLE
Terms need to be imported

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#190]
ID | Label | Comment
-- | -- | --
APOLLO_SV:00000570 | Employment status | in PR under 'employment information'
ARO:3004306 | Methicillin resistant Staphylococcus aureus | in PR under 'antimicrobial agent resistance phenotype'
CHEBI:22723 | Compound benzoic acid | in PR under 'molecular entity'
CMO:0000105 | BMI | in PR under 'scalar measurement datum'
CMO:0000591 | Urine protein | in PR under 'scalar measurement datum'
DOID:1395 | Schistosomiasis | in PR under 'parasitic helminthiasis infectious disease' (computed)
DOID:28 | Endocrine condition | in PR under 'disease of anatomical entity' (computed)
DOID:4483 | Runny nose or nasal congestion | in PR under 'upper respiratory tract disease' (computed)
DOID:635 | AIDS | in PR under 'human immunodeficiency virus infectious disease' (computed)
DRON:00001126 | Ceftriaxone injection | In PR under 'drug solution' (computed)
DRON:00017034 | Ketotifen | not in PR - should replace w/CHEBI:92511
DUO:0000001 | Data access level | in PR under 'data item'
ENVO:01000739 | Habitat | in PR under 'material entity' (computed)
ENVO:01000773 | Village | in PR under 'environmental zone' (computed)
FLU:0001025 | Passage history | not in PR - should replace w/OBI_0002748
GAZ:00000013 | Continent | in PR under 'geographic location'
HP:0000478 | Eye | in PR under 'Phenotypic abnormality' (computed)
HP:0000707 | Neurological | in PR under 'Phenotypic abnormality' (computed)
HP:0001518 | Small for gestational age | in PR under 'Decreased body weight' (computed)
HP:0001557 | Fetal movement | in PR under 'Abnormality of prenatal development or birth' (computed)
HP:0001574 | Skin | in PR under 'Phenotypic abnormality' (computed)
HP:0001595 | Abnormal hair | in PR under 'Abnormality of the integument' (computed)
HP:0001787 | Delivery complications | in PR under 'Abnormality of prenatal development or birth' (computed)
HP:0001897 | Severe normocytic anemia | in PR under 'Abnormality of blood and blood-forming tissues' (computed)
HP:0001919 | Acute kidney injury | in PR under 'Renal insufficiency' (computed)
HP:0001942 | Metabolic acidosis | in PR under Acidosis (computed)
HP:0002015 | Dysphagia | in PR (2 parents computed)
HP:0002086 | Respiratory | in PR under 'Phenotypic abnormality' (computed)
HP:0002094 | Shortness of breath | in PR under ''Abnormal respiratory system physiology' (computed)
HP:0002151 | Hyperlactataemia | in PR under Acidosis (computed)
HP:0003641 | Hemoglobinurea | in PR under 'Abnormality of urine homeostasis' (computed)
HP:0003811 | Neonatal death | in PR under 'clinical history'
HP:0003826 | Stillbirth | in PR under 'clinical history'
HP:0005268 | Spontaneous abortion | in PR under 'Abnormal delivery' (computed)
HP:0011024 | Gastrointestinal | in PR under 'Abnormality of the digestive system' (computed)
HP:0012211 | Renal impairment | in PR (2 parents computed)
HP:0100518 | Dysuria | in PR under 'Abnormality of the urinary system' (computed)
HP:0100602 | Pre-eclampsia | in PR under 'Abnormality of prenatal development or birth' (computed)
SNOMEDCT:224619008 | Migrant | in PR under 'Homo sapiens'
SNOMEDCT:40541001 | Acute pulmonary edema | in PR under 'Pulmonary edema'
SNOMEDCT:83088009 | Acinetobacter lwoffi | not in PR - should replace with NCBITaxon_28090
EFO:0000319 | Cardiovascular condition | not in PR - may need to replace w/EUPATH term if we keep 'immediate clinical history'
EFO:0004344 | Birth weight (kg) | in PR under 'mass measurement datum'
EFO:0009663 | Genitourinary condition | in PR under 'disease of anatomical entity'
EFO:1001491 | Abortion type | in PR under EFO:0009663 (1 row above)
ONS:0000106 | 24hr food recall | in PR under document
NCBITaxon:11118 | Coronavirus | not in PR - should replace w/NCBITaxon:2501931
NCBITaxon:222 | Achromobacter | in PR (computed parent)
NCBITaxon:40323 | Stenotrophomonas | in PR (computed parent)
NCBITaxon:59732 | Chryseobacterium | in PR (computed parent)
NCIT:C120707 | Mixed Commensal Flora | in PR under 'collection of organisms'
NCIT:C120835 | Elective abortions (count) | in PR under count
NCIT:C120837 | Spontaneous abortions (count) | in PR under count
NCIT:C124435 | Gestational age at delivery (weeks) | in PR under 'gestational age measurement datum'
NCIT:C131844 | Edinburgh postnatal depression scale | in PR under document
NCIT:C154876 | Fundal height (cm) | in PR under 'length measurement datum'
NCIT:C173766 | Severe Acute Respiratory Infection (SARI) | in PR under 'respiratory system disease'
NCIT:C25632 | Province | not in PR - should use 'first -order administrative region' from ENVO
NCIT:C25641 | Reference | not in PR - should use IAO term for reference
NCIT:C43428 | Zone | This is an issue because it refers to both second- and third- order administrative regions in ClinEpi
NCIT:C50996 | Protocol deviations | in PR under ICE
NCIT:C53693 | Canine breed | not in PR - see issue #104
NCIT:C64593 | Bed time | in PR under 'time measurement datum'
NCIT:C69121 | Trimester | in PR under 'time measurement datum'
NCIT:C81236 | Infant birth complications | not in PR, suggest replacing with HP:0001197
NCIT:C81257 | First day of last menstrual period | not in PR, suggest replacing with ONTONEO:00000125
NCIT:C83101 | Visit number | in PR under count
NCIT:C90491 | Pregnancy outcome | in PR under 'clinical data item'
NCIT:C92791 | Fetal heart tones | in PR under 'clinical finding'
NCIT:C92867 | Abdomical pain/contractions | this ID refers to regularity of contractions - instead we should use NCIT:C92904
NCIT:C92913 | Vaginal bleeding | in PR under 'clinical finding'
OAE:0000001 | Adverse events | in PR under process
OBCS:0000106 | Cohort | in PR under 'study design'
OBCS:0000107 | Randomized controlled/clinical trial | in PR under 'study design'
OBI:0000115 | Experimental | in PR under 'study design' (computed)
OBI:0002460 | Population included | in PR under 'eligibility criterion' (computed)
OBI:0002507 | Saliva sample | in PR under 'specimen from organism' (computed)
OBI:0002608 | Oropharyngeal swab sample | in PR under 'swab specimen' (computed)
OBI:0002674 | Case series | in PR under 'study design' (computed)
OBI:2000012 | Umbilical cord blood sample | in PR under 'bodily fluid specimen' (computed)
OMIABIS:0001011 | Participant count | in PR under count
OMIABIS:0001018 | Cross-sectional | in PR under 'study design'
SYMP:0000116 | Prostration | in PR under 'Phenotypic abnormality'
SYMP:0000505 | Sore throat | not in PR - should replace with HP:0033050
SYMP:0019176 | Malaise | in PR under 'Phenotypic abnormality'

**Comment by johnwjudkins** [comment]
I suggest the following changes:
- Replace [SNOMED A. lwoffii](http://purl.bioontology.org/ontology/SNOMEDCT/224619008) with [NCBITaxon A. lwoffii](http://purl.obolibrary.org/obo/NCBITaxon_28090).
- [Cardiovascular condition](http://www.ebi.ac.uk/efo/EFO_0000319) is in the context of immediate clinical history, so this should be a EUPATH term (should use DOID term for cardiovascular system disease anyway).
- Replace [the family coronaviruses are in](http://purl.obolibrary.org/obo/NCBITaxon_11118) with [the coronavirus itself](http://purl.obolibrary.org/obo/NCBITaxon_2501931).
- Regarding NCIT terms Province & Zone, we replaced [country name](http://purl.obolibrary.org/obo/OBI_0001627) with [administrative region](http://purl.obolibrary.org/obo/ENVO_00000004). However, it looks like [national geopolitical entity](http://purl.obolibrary.org/obo/ENVO_00000009) is the ENVO term for a country and [first-order administrative region](http://purl.obolibrary.org/obo/ENVO_00000005) is the ENVO term for state or province. "Zone" is problematic, being 2nd-order in Ethiopia but 3rd-order in Malawi.
- Replace [NCIT:Reference](http://purl.obolibrary.org/obo/NCIT_C25641) with [IAO:reference](http://purl.obolibrary.org/obo/IAO_0000320).
- Replace [Birth complication](http://purl.obolibrary.org/obo/NCIT_C81236) with [Abnormality of prenatal development or birth](http://purl.obolibrary.org/obo/HP_0001197).
- Replace [Last menstrual period](http://purl.obolibrary.org/obo/NCIT_C81257) with [date of last menstruation](http://purl.obolibrary.org/obo/ONTONEO_00000125).
- Replace [Regular Uterine Contraction](http://purl.obolibrary.org/obo/NCIT_C92867) with [Uterine Contraction](http://purl.obolibrary.org/obo/NCIT_C92904).
- Replace [SYMP](http://purl.obolibrary.org/obo/SYMP_0000505) with [HP](http://purl.obolibrary.org/obo/HP_0033050) for sore throat.

MICRO:0000494 is described as a "participant identifier" in MicrobiomeDB, but is 'aerobic' in MicrO.owl, so I'm not sure what to do for this term. According to issue #104, 'Dog breed' is no longer used - should I add it?

I will make a pull request for those changes which are suggested in Jie's table but are not already addressed in this comment (because the terms addressed in this comment need discussion).
I have also updated the hierarchy under 'clinical data item' to match that of OGMS.

**Comment by zhengj2007** [comment]
I removed MICRO:0000494, since we don't know what it means. So, we don't give it EUPATH ID.
