### ISSUE TITLE
NTRs: mosquito magnet liberty plustm catch AND lurex 

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#303]
Hello! Pretty please can we add these terms:

term:mosquito magnet liberty plustm catch
definition: The Mosquito Magnet LibertyTM is one of the propane-powered traps that uses a counterflow technology to emit a plume of CO2, heat, and water vapor.

term:lurex
defintion: Lurex is a mosquito attractant that mimics naturally occurring human skin scents or odors known to attract mosquitoes.

**Comment by johnwjudkins** [comment]
label: Mosquito Magnet Liberty Plus
definition: An arthropod trap that is manufactured by the American Biophysics Corporation and is designed with counterflow technology, allowing it to draw air into the device as it expels carbon dioxide, in order to draw in arthropods attracted to it.
parent: arthropod trap

label: Lurex
definition: An arthropod attractor that is manufactured by the American Biophysics Corporation and has L-lactic acid as its active ingredient in order to mimic the scent of human skin.
parent: arthropod attractor

**Comment by zhengj2007** [comment]
@SAK22 Could you please review the labels and definitions? Thanks!

**Comment by SAK22** [comment]
@zhengj2007 labels and definitions look great!

**Comment by zhengj2007** [comment]
@johnwjudkins Could you please help on adding the terms in the ontology?

**Comment by zhengj2007** [comment]
I checked the ontology. The existing mosquito traps are added in the OBI and imported to the VEuPathDB ontology. I think we should submit 'Mosquito Magnet Liberty Plus' to OBI. I propose the label as 'Mosquito Magnet Liberty Plus trap' and add 'Mosquito Magnet Liberty Plus' as alternative label.

**Comment by zhengj2007** [comment]
For term 'Lurex', I think we'd better to label it as 'lurex attractant' for clarification and better to add logical axiom related to  L-lactic acid, http://purl.obolibrary.org/obo/CHEBI_422

**Comment by SAK22** [comment]
> I checked the ontology. The existing mosquito traps are added in the OBI and imported to the VEuPathDB ontology. I think we should submit 'Mosquito Magnet Liberty Plus' to OBI. I propose the label as 'Mosquito Magnet Liberty Plus trap' and add 'Mosquito Magnet Liberty Plus' as alternative label.
> 
> Hi @SAK22, we already have the term 'Mosquito Magnet trap' with definition, 'An arthropod trap that is powered by propane and is designed to emit a combination of carbon dioxide, heat, water, and oct-1-en-3-ol attractants while simultaneously using suction to trap arthropods.' Is 'Mosquito Magnet Liberty Plus' a kind of 'Mosquito Magnet trap'?

Hi @zhengj2007 yes it is a type of mosquito magnet you are correct.

**Comment by zhengj2007** [comment]
Thanks @SAK22

@johnwjudkins We should add 'Mosquito Magnet Liberty Plus trap' as a subClass of 'Mosquito Magnet trap'

**Comment by johnwjudkins** [comment]
https://github.com/obi-ontology/obi/issues/1523

**Comment by johnwjudkins** [comment]
@SAK22 Can you explain how the Liberty Plus is different from other Monster Magnet traps? Thanks.

**Comment by SAK22** [comment]
@johnwjudkins I am trying to click on the link in this page under 'products' that says compare traps to see the difference but it doesn't seem to go anywhere for me? Does it for you?
https://www.mosquitomagnet.com/store/mosquito-magnet-trap/executive/traps

**Comment by johnwjudkins** [comment]
The link works for me, but the problem is the Liberty Plus trap is discontinued, so only accessories for it appear for sale on the website.

**Comment by johnwjudkins** [comment]
@SAK22 The original IRO term 'mosquito magnet pro catch' had this definition: "The Mosquito Magnet ProTM (MMP) is one of the propane-powered traps that uses a counterflow technology to emit a plume of CO2, heat, and water vapor. The MMP also utilizes octenol as an attractant."

However, the associated term submitted to OBI is 'Mosquito Magnet trap' defined as "An arthropod trap that is powered by propane and is designed to emit a combination of carbon dioxide, heat, water, and oct-1-en-3-ol attractants while simultaneously using suction to trap arthropods."

I think the original IRO term meant to represent the Pro trap as opposed to other traps by MM like Liberty Plus. So I think we need to find a way to compare the Pro with the Liberty Plus.

**Comment by johnwjudkins** [comment]
@SAK22 So we want: a general term for Mosquito Magnet trap, one for the Pro trap, and one for the Liberty Plus trap. Please help us determine the differences between them.

**Comment by SAK22** [comment]
Yes I think you are right re the general parent term @johnwjudkins , I am trying to work out the difference and can now only find executive and patriot on their site: https://www.mosquitomagnet.com/advice/all-about/compare-traps , I will see if I can find out elsewhere!

**Comment by SAK22** [comment]
@johnwjudkins emailed their customer support to see if they can make it clearer for us.

**Comment by SAK22** [comment]
@johnwjudkins , this did not help much!
Hello Sarah,

Thank you for reaching out to us. We appreciate your interest in our products! Both of these models have been obsolete for several years and comparison information is not available.

Please feel free to contact us with any questions, we're happy to help.

**Comment by johnwjudkins** [comment]
@SAK22 I came up with this:

Label:
Definition: An arthropod trap that is designed to emit a combination of carbon dioxide, heat, water, and oct-1-en-3-ol attractants while simultaneously using suction to trap arthropods. This trap has the same design as the Mosquito Magnet Pro trap but is smaller, is more lightweight, and uses a main line electricity supply instead of propane to power itself. Both use propane to produce the arthropod attractor.

If this sounds right to you, I'll submit it to OBI. Also, if it sounds right to you, I'll have them edit the label for ['Mosquito Magnet trap'](http://purl.obolibrary.org/obo/OBI_0002933) to be 'Mosquito Magnet Pro trap'. I think that one was meant to be the Pro version since its source is IRO:0000022.

**Comment by SAK22** [comment]
@johnwjudkins I am happy with the above :)

**Comment by zhengj2007** [comment]
Add the notes about this issue in the release notes.
