### ISSUE TITLE
NTR: Tick developmental stages

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#338]
Hello,

I am not sure would I need to add new terms for this developmental stages specifically for ticks? or can I use other terms?

nymph

**Comment by SAK22** [comment]
I will just need the term nymph :) 
I used larva and adult terms that we use in mosquito work from IDOMAL

**Comment by zhengj2007** [comment]
Since IDOMAL is inactive, we need to replace the IDOMAL terms with other active OBO Foundry ontology terms.

Regarding nymph, do this term work for you @SAK22 :
http://purl.obolibrary.org/obo/UBERON_0000070 pupal stage

If so, for other terms, you may consider:
http://purl.obolibrary.org/obo/UBERON_0000069 larval stage
http://purl.obolibrary.org/obo/UBERON_0000066 fully formed stage (adult stage)

**Comment by zhengj2007** [comment]
http://purl.obolibrary.org/obo/UBERON_0014405 nymph stage
http://purl.obolibrary.org/obo/UBERON_0000069 larval stage
http://purl.obolibrary.org/obo/UBERON_0000066 fully formed stage (adult stage)

@SAK22 Here is the tick development stage terms you can use.

**Comment by SAK22** [comment]
THANK YOU!
