### ISSUE TITLE
NTR: cow-baited tent collection

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#396]
For new term requests, please provide the following information:
**Term Label** cow-baited tent collection

**Definition** [required except for organism name]
An adult cow was loosely tied to a stake in the ground at the centre of a large tent. Mosquitoes resting on the interior walls of the tent were collected hourly for 5 min using mouth aspirators. 

**Suggested Parent Term** [required]
Please look in the ontology hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/eupath) or choose one from following list: 
Material - device

**Comment by johnwjudkins** [comment]
@SAK22 Would the tent be considered a baited net trap? In other words, are the mosquitoes prevented from either leaving the tent or biting the cow?

**Comment by zhengj2007** [comment]
Will chat with @SAK22 to understand what she needs.

**Comment by johnwjudkins** [comment]
Label: cow-baited arthropod trap
Definition: A resting arthropod trap that consists of a tent inside which an adult cow is tethered to the ground, in order to attract arthropods and collect those that rest on the interior walls of the tent.
Parent: resting arthropod trap

It seems more like a description of a particular device (rather than details of a method/process for collecting), so I'm proposing it as another trap term. Let me know whether that works for you @SAK22 .

**Comment by SAK22** [comment]
That sounds good to me @johnwjudkins !

**Comment by johnwjudkins** [comment]
We have the other arthropod trap terms in OBI, so I'm submitting it there: https://github.com/obi-ontology/obi/issues/1602

**Comment by johnwjudkins** [comment]
At the next OBI release, this term will be added as OBI_0003481.
