### ISSUE TITLE
NTR: Unmapped column headers for the MicrobiomeDB new study

### ISSUE THREAD

**Issue by weili-apidb** [VEuPathDB-ontology/VEuPathDB-ontology#399]
Raw metadata from Dan: 
https://docs.google.com/spreadsheets/d/150tNclF2HrXq6LOh8wJOCtz9XF8Yeui9m6Vv_2rpbJ8/edit#gid=0

The ISA simple file prepared by Wei:
https://github.com/VEuPathDB/ApiCommonMetadataRepository/blob/master/ISA/metadata/MBSTDY0021/FARMM_metagenomics.txt

Workflow failures:
Unmapped column headers:  antibiotics, host_body_mass_index, host_height

**Comment by dpbisme** [comment]
A bit more info for @zhengj2007 regarding these unmapped headers:
1. antibiotics - this refers to whether the sample was collected from a participant before (pre antibiotics) during (antibiotic treatment) or after (post antibiotics).
2. host_body_mass - This should be loaded as 'Weight (kg)', which is a display term variable we currently have for at least one other study.
3. host_height - We actually need a new variable for this, since we don't currently have height for any other studies (which is surprising).  This data is height in cm.

**Comment by zhengj2007** [comment]
I think all the terms are available for use.

1. antibiotics - EUPATH_0009125 Antibiotic medication related to sample collection
2. host_body_mass - IAO_0000414 weight 
3. host_height - EUPATH_0010075 height

Are the mappings good for you? @weili-apidb @dpbisme

**Comment by dpbisme** [comment]
Looks good to me, @zhengj2007!  Thanks.
