### ISSUE TITLE
NTR: PopBio study name

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#406]
**Term Label** [required]

PopBio study name

**Synonyms** [optional]

Study name

**Definition** [required except for organism name]

The name or title of an individual study that forms part of the VectorBase population biology resource

**Suggested Parent Term** [required]

For use in study_classifications owl file.

**Comment by zhengj2007** [comment]
Proposed changed on the definition:
An investigation title denotes a study that forms part of the VectorBase population biology resource.

Will discuss on Oct 12 ontology call.

**Comment by johnwjudkins** [comment]
I would use "An investigation title that denotes a study that forms part of the VectorBase population biology resource."

**Comment by zhengj2007** [comment]
Bob: For reasons I'm not easily able to explain, we need to add a "Study name" field to the [Study Classifications owl file](https://github.com/VEuPathDB/ApiCommonData/blob/master/Load/ontology/General/study_classifications/classifications.owl) (this is what drives the "Study summaries table" in Clinepi) because we are using this also for popbio. I would naturally want to use investigation title (OBI_0001622) for this, but that is already being used for "Project name" in the same owl file, which contains values such as ICEMR, GEMS, GATES, etc.
Is there some way we can resolve this?  Is it easy to change "Project name" to another IRI? Maybe IAO_0000303 [institutional identification](https://ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/IAO_0000303) or IAO_0000624 [funding source declaration textual entity](https://ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/IAO_0000624) or request a new OBI term "Umbrella research network name" or similar?
Or is there some other IRI I can use for "Study title"?  I've searched the VEuPath ontology and can't find a good one

**Comment by zhengj2007** [comment]
Discussed on 2022-10-12 ontology team meeting.

@bobular: @cstoeckert would like to know whether the term is used internally. If so, we can assign an EUPATH ID to the term and used as a placeholder and no need to add in the ontology.

**Comment by zhengj2007** [comment]
@bobular Sounds good. We will assign an EUPATH ID to it. Do we need to add the term in [Study Classifications owl file](https://github.com/VEuPathDB/ApiCommonData/blob/master/Load/ontology/General/study_classifications/classifications.owl)?

**Comment by bobular** [comment]
Yes please! [Here](https://github.com/VEuPathDB/ApiCommonData/blob/master/Load/ontology/General/study_classifications/classifications.owl#L418-L421) please.

**Comment by zhengj2007** [comment]
Assigned ID, EUPATH_9990001, to term 'Study name' and update the ID in study classification OWL file.
