### ISSUE TITLE
Parent of term 'gestational age measurement datum'

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#422]
**Describe the bug**

ONTONEO_00000255 'gestational age measurement datum' imported as a subClassOf 'data item'. Should it be the child of 'age measurement datum'?

**Comment by johnwjudkins** [comment]
This term is set up so its parent is computed by Ontofox, so I don't know why it places it under 'data item' rather than 'age measurement datum' as Ontobee shows. I could update it by explicitly declaring its parent in the input file, but if I do that, it won't update if ONTONEO changes its hierarchy again.

**Comment by zhengj2007** [comment]
You can add the term 'age measurement datum' in ONTONEO input file. So, it will can include in the 'includeComputedIntermediates' Ontofox import. The term will be removed by following ROBOT command. So, it should be fine.
