### ISSUE TITLE
NTR: UV light

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#76]
Please could we add UV light under the parent term attractant?

**Comment by cstoeckert** [comment]
attractor role applies to material entity. Have photon which has energy that can have a frequency associated with that energy. However, ultraviolet radiation is defined as a process which can not bear a role. Quantum mechanics!? 
Instead of UV light - could we say UV light source which then makes thing a lot simpler because we know how to define that as a type of light source and can for the moment associate with the arthropod attractor role.

**Comment by SAK22** [comment]
O wow yes of course! Let's do that. I would need to change the current term 'light' to 'visible light' or whatever you see fit that means that bit more ontologically correct! Then add a new parent term 'light' to encompass visible light and UV light source. So that all the historical data in VB with the term 'light' keep the same term number when changing to 'visible light'. If that makes sense?

**Comment by cstoeckert** [comment]
I think we may have those covered already:
see http://purl.obolibrary.org/obo/OBI_0400065 'light source' for general term and under it we have different types such as http://purl.obolibrary.org/obo/EUPATH_0000253 'solar light source' but can make a term like 'visible light source' if needed.

**Comment by zhengj2007** [comment]
EUPATH_0043065 'UV light source' 
EUPATH_0043066 'visible light source'

**Comment by cstoeckert** [comment]
This belongs in a more general ontology like OBI.

**Comment by zhengj2007** [comment]
If OBI accept the terms, we may remove the terms from VEuPathDB rather than deprecate them since they are only in development version. 

Besides, shall we also submit term 'solar light source' to OBI?

**Comment by cstoeckert** [comment]
Agree with both.

**Comment by zhengj2007** [comment]
The terms have been added in OBI and will be available in next OBI release.

OBI_0002900	ultraviolet light source
OBI_0002901	 visible light source
OBI_0002902	solar light source
