### ISSUE TITLE
NTR: World Health Organization core health indicator subdomain

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#78]
ID: EUPATH_0000763 (in use in classifications.owl)

Label: World Health Organization core health indicator subdomain

Definition: An information content entity that is about some quality, risk, or access to health care that inheres in a human being and is deemed clinically significant by the World Health Organization, which uses this entity to categorize each of their individual core health indicators, based on the type of quality, risk, or access.

This definition is based on the [WHO 2018 Global Reference List of 100 Core Health Indicators](https://apps.who.int/iris/bitstream/handle/10665/259951/WHO-HIS-IER-GPM-2018.1-eng.pdf;jsessionid=328D523A9FE9264322E2A333924FD508?sequence=1) and follows ICO and SDGIO's understanding of risk and access as specifically dependent continuants.

**Comment by cstoeckert** [comment]
From Brianna L: 
I'm not sure if this matters or not but this portion caught my eye, "inheres in a human being" note that the core health indicators are not on an individual level. Meaning that they are calculated on a population basis and are dependent upon measurements taken on a population. An example would be: "Coverage of diarrhea treatment" while the components of the indicator are computed from individual data points; the indicators do not refer to information about an individual rather a population.
Otherwise, looks good.

**Comment by johnwjudkins** [comment]
Revised definition based on Brianna's feedback:

An information content entity that is used by the World Health Organization to categorize each of their individual core health indicators, which identify statistical data the organization deems clinically significant on the prevalence of some quality, risk, or access to health care in members of a population.

**Comment by johnwjudkins** [comment]
Updated in eupath_dev.owl
